### ISSUE TITLE
V0.3 Feedback

### ISSUE THREAD

**Issue by crphang** [CS2103AUG2016-W14-C2/main#59]
# User Guide
- Some of the areas have formatting issues:
1. The spaces in between sections are not consistent.
2. The examples part for `modify` : "modify storage path user/Desktop" is not added as a codeblock.
- You might want to be clearer for the format part. Specifically, you might want to use square brackets to denote certain portion as optional: `Task and event are differentiated by the input of time tag. Each activity can have any number of notes (including 0). Each note is limited to 140 characters.` You can also consider creating another subsection for each of the add commands. Right now it looks rather complex. 
- The 'Command summary' section will be used heavily by our testers. Try to make it easy to use as possible. e.g. give examples for each command.
- You would also like to have some screenshots to explain some of your examples better.
# Developer Guide
- Minor Problem Here:
  ![image](https://cloud.githubusercontent.com/assets/4986717/19563647/61c57a08-9713-11e6-9fbb-f99cf09c0d36.png)

The invocation for `post(ActivityManagerChangedEvent)` from UI to Event has the arrow starting from UI. Compare it to the original: 

![image](https://cloud.githubusercontent.com/assets/4986717/19563785/ded1c1a0-9713-11e6-9dce-ad643e4606ec.png)

The thing to consider is whether UI actually made the method call to EventsCenter.
- Be careful with your arrows:

![image](https://cloud.githubusercontent.com/assets/4986717/19563872/291c9442-9714-11e6-918d-f89f6d74c3b9.png)
1. The green arrow from UI should originate from outside the Logic box.
2. Your output to UI follow suit as well.
- Be consistent with your white spaces between sections.

**Comment by crphang** [comment]
# Additional Developer Guide Comments
- Since you guys are not planning to use browser panel, update your Developer's Guide to fit that. 
- Does main window have Event Task Panel, Floating Task Panel, Task Panel. Or does ActivityListPanel have each of those cards?
  ![image](https://cloud.githubusercontent.com/assets/4986717/19565258/d00d6606-9718-11e6-8fbc-d0fe1cf8d557.png)

**Comment by lowjiansheng** [comment]
Noted
